var itemStr = [['\nHow to recycle\n\nAcetylene Oxygen Tanks\nDrop-off locations\nContact the supplier or manufacturer. In most cases, they will take the tank back at no cost.\nIf the supplier refuses to accept the tank, call (206) 296-4692. You will need to request approval to bring the tank to a household hazardous waste facility.\n\n'],
  ['\nHow to recycle\n\nAcoustic Ceiling Tile\nIn garbage\nCeiling tiles that don\xe2\x80\x99t contain asbestos can go in the garbage:\n\nItems must fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nDrop-off locations\nBring acoustic ceiling tiles that don\xe2\x80\x99t contain asbestos to city transfer stations. Fees apply.\nHazardous\nIf you believe the ceiling tile contains asbestos, contact the Puget Sound Clean Air Agency at (206) 343-8800.\n\n'],
  ['\nHow to recycle\n\nAerosol Cans\nHazardous \xe2\x80\x93 no charge\nBring cans that contain hazardous materials like paint, solvents, or other flammables to a household hazardous waste facility. No fee.\nIn garbage\n\nEmpty aerosol cans\nPartially full cans with non-hazardous contents\n\n\n'],
  ['\nHow to recycle\n\nAir Conditioners or Heat Pumps\nDonate and reuse\nDonate air conditioners or heat pumps in good condition to local thrift stores. Call first to determine acceptance policies.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item pickup. {{proj[6].rate_text}}\nTransfer station\nBring damaged air conditioners and heat pumps to city transfer stations. {{proj[0].rate_text}}\n\n\n'],
  ['\nHow to recycle\n\nAluminum\nIn recycling\n\nMetal parts larger than 3-inches go in the recycling.\n\nNext to bin \xe2\x80\x93 no charge\n\nLarge metal parts can be put at the curb for pickup on your recycling collection day.\nThese must be bundled or tied.\nThe maximum size is 2-feet on all sides.\n\nIn garbage\n\nMetal items with plastic, wood, or rubber attached\nMetal items that are smaller than 3-inches\n\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item collection. Fees apply.\nDrop-off locations\n\nAll metal, except car parts, is accepted as recycling at city transfer stations. There is no charge for recycling at the transfer station.\nMaximum size is 8-feet long.\nThere is a charge for appliances, limit 2 per load.\n\n\n'],
  ['\nHow to recycle\n\nAluminum Foil\nIn recycling \xe2\x80\x93 rinse first\n\nAluminum foil \xe2\x80\x93 don\xe2\x80\x99t crumple into a ball\nAluminum food pans\n\nIn garbage\n\nDirty or food-covered aluminum foil or food pans\nWine bottle foil\n\n\n'],
  ['\nHow to recycle\n\nAmmunition or Guns\nHazardous\nCall the Seattle Police Firing Range at (206) 684-7470 to dispose of ammunition or firearms.\n\n'],
  ['\nHow to recycle\n\nAntifreeze\nHazardous \xe2\x80\x93 no charge\nBring antifreeze to a household hazardous waste facility:\n\nAll containers must be 5-gallons or less.\nLimit 50-gallons per trip.\n\nDid you know?\nAntifreeze is harmful to people, animals, and the environment and should never be poured down drains, toilets, or on the ground.\n\n'],
  ['\nHow to recycle\n\nOther Large Appliances\nReuse\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request  bulky item pickup. {{proj[6].rate_text}}\nTransfer station\nBring up to 2 residential appliances per visit to city transfer stations. {{proj[2].rate_text}}\n\n'],
  ['\nHow to recycle\n\nAsbestos\nHazardous\nBring to an asbestos disposal facility.\nDid you know?\nBecause asbestos is harmful to people, animals, and the environment, it must be disposed of at designated facilities.\n\n'],
  ['\nHow to recycle\n\nAseptic or Tetra Pak\nIn recycling \xe2\x80\x93 rinse first\n\nEmpty milk, juice, and soup cartons\nCartons labeled Tetra Pak\nOther aseptic cartons\n\nPlastic spouts don\xc3\xa2\xc2\x80\xc2\x99t need to be removed to recycle Tetra Pak cartons. Caps should be removed and placed in the garbage.\n\n'],
  ['\nHow to recycle\n\nFireplace or Briquette Ashes\nIn garbage\nFireplace and briquette ashes must be completely cooled, wetted, and placed in a closed box or bag. This prevents ash from scattering when your garbage is collected.\n\n'],
  ['\nHow to recycle\n\nAsphalt Roofing\nIn garbage\nAsphalt roofing that doesn\xe2\x80\x99t contain asbestos can go in the garbage:\n\nItems must fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nDrop-off locations\nBring asphalt roofing shingles that don\xe2\x80\x99t contain asbestos to city transfer stations. Fees apply.\nHazardous\nIf you believe the roofing contains asbestos, contact the Puget Sound Clean Air Agency at (206) 343-8800.\n\n'],
  ['\nHow to recycle\n\nMedicine Bottles - Over the Counter\nIn recycling\nPill bottles, such as aspirin or vitamin bottles, go in the recycling.\nIn garbage\nPlastic prescription medicine vials go the garbage.\nDrop-off locations\nBring medicines to a secure medicine return site.\n\n'],
  ['\nHow to recycle\n\nStereo or Audio Equipment\nDonate and reuse\nDonate stereo or audio equipment in good condition to local thrift stores.\nResell or give them away using sites like Craigslist, Freecycle, and Buy Nothing.\nFind locations to recycle studio and audio equipment via the Take It Back Network (fees may apply).\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. {{proj[4].rate_text}}\nDid you know?\nStudio and audio equipment can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\n\n'],
  ['\nHow to recycle\n\nPaper Bags\nIn recycling\nClean and dry paper bags go the recycling.\nIn food and yard waste\nFood-soiled bags go in the food and yard waste cart.\n\n'],
  ['\nHow to recycle\n\nBread Bags\nIn garbage\nPlastic bread bags go in the garbage.\nDid you know?\nThese plastic food bags often contain food residue and moisture that can contaminate recycling.\n\n'],
  ['\nHow to recycle\n\nGrocery or Shopping Bags\nIn recycling\n\nClean and empty plastic grocery bags \xe2\x80\x93 bundle into one bag and tie off\nClean and dry paper bags or paper sacks\n\nIn food and yard waste\n\nPaper bags that are wet or food-soiled\n\nIn garbage\n\nPlastic bags that are wet or food-soiled\nPlastic produce bags\nSingle plastic bags\n\nDid you know?\nSingle plastic bags go in the garbage because they jam the machinery at the recycling facility. Produce bags are not recyclable because they often contain food or moisture that contaminate the recycling.\n\n'],
  ['\nHow to recycle\n\nProduce or Bulk Food Bags\nIn garbage\nPlastic bags used for produce and bulk foods go in the garbage.\nDid you know?\nThese bags are not recycled because they often contain food residue or moisture.\n\n'],
  ['\nHow to recycle\n\nZiploc Bags\nIn garbage\nZiploc or other plastic food bags go in the garbage.\nDid you know?\nZiploc and plastic food bags contain more than one type of plastic that can\xe2\x80\x99t be recycled together. They also often contain food residue and moisture that contaminate recycling.\n\n'],
  ['\nHow to recycle\n\nBarrels or Drums\nHazardous\nSealed drums and drums that held hazardous waste must go to King County Household Hazardous Waste.\nDrop-off locations\nBring barrels and drums that held non-hazardous material to city transfer stations:\n\nEmpty barrels and drums must be clean and cut in half.\nClean metal can be recycled for no fee.\n\nIn garbage\nPlastic and dirty metal drums that held non-hazardous material can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nAlkaline Batteries\nDrop-off locations\nBring alkaline batteries to city transfer stations. No fee.\nBring alkaline batteries to a household hazardous waste facility where the materials in the batteries will be reclaimed and recycled. No fee.\nIn garbage\nNon-rechargeable, household alkaline batteries (such as AAA, AA, C, D, or 9-volt) can go in the garbage.\nHousehold hazardous waste facility\nBring alkaline batteries and rechargeable batteries to a household hazardous waste facility, where the materials in the batteries will be reclaimed and recycled. No fee.\n\n'],
  ['\nHow to recycle\n\nRechargeable Batteries\nDrop-off locations\nBring rechargeable batteries to city transfer stations. No fee.\nBring rechargeable batteries to a household hazardous waste facility where the materials in the batteries will be reclaimed and recycled. No fee.\nFind drop off and mail back recycling options at Call2Recycle outlet.\nRechargeable batteries can not go in the garbage or recycling cart\n\n'],
  ['\nHow to recycle\n\nBed Frames\nDonate and reuse\nDonate bed frames in good condition to local thrift stores.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item pickup. {{proj[6].rate_text}}\nTransfer station\nBring bed frames to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nBedding or Linens\nDonate\nStained, worn out, ripped, or damaged bedding, linens, towels, and other fabrics can be turned into new products through Threadcycle. Some local thrift and second-hand stores are partners and will accept these items at their regular collection or drop box locations.\nIn garbage\nBedding, linens, towels, and other fabrics can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nPlastic Berry Trays\nIn recycling \xe2\x80\x93 rinse first\nPlastic berry trays larger than 3-inches on any side go in the recycling.\n\n'],
  ['\nHow to recycle\n\nBeverage Cans\nIn recycling \xe2\x80\x93 rinse first\nEmpty soda and beverage cans go in the recycling.\nDid you know?\nUsing recycled aluminum to make things takes 98% less energy than using new material.\n\n'],
  ['\nHow to recycle\n\nBicycles or Bike Parts\nIn recycling\nClean metal bike parts 3-inches or larger can go in the recycling:\n\nItems must fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nDrop-off locations\nDonate or resell usable bikes and parts to scrap metal dealers or community-oriented bike shops like Bike Works or Recycled Cycles.\nBring bikes and parts to city transfer stations to be recycled. No fee.\nIn garbage\nBike parts smaller than 3-inches go in the garbage.\n\n'],
  ['\nHow to recycle\n\nBicycles or Bike Parts\nIn recycling\nClean metal bike parts 3-inches or larger can go in the recycling:\n\nItems must fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nDrop-off locations\nDonate or resell usable bikes and parts to scrap metal dealers or community-oriented bike shops like Bike Works or Recycled Cycles.\nBring bikes and parts to city transfer stations to be recycled. No fee.\nIn garbage\nBike parts smaller than 3-inches go in the garbage.\n\n'],
  ['\nHow to recycle\n\nBleach\nHazardous \xe2\x80\x93 no charge\nBring partially full containers of chlorine bleach to a household hazardous waste facility. No fee.\nIn recycling \xe2\x80\x93 rinse first\nEmpty and rinsed bleach bottles go in the recycling.\n\n'],
  ['\nHow to recycle\n\nBlister Packages\nIn garbage\nPut blister packages in the garbage. They aren\xe2\x80\x99t recyclable.\nBlister packages are the clear hard-to-open plastic packaging from items such as batteries and small electronics.\n\n'],
  ['\nHow to recycle\n\nHardcover Books\nIn garbage\nHardcover books can go in the garbage.\nDid you know?\nHardcover books can\xe2\x80\x99t be recycled due to the glue in the binding.\n\n'],
  ['\nHow to recycle\n\nPaperback Books\nIn recycling\nPaperback books can go in your recycling bin.\n\n'],
  ['\nHow to recycle\n\nBottle Caps or Jar Lids\nIn recycling\n\nSmall plastic bottle caps if screwed onto an empty plastic bottle\nLoose plastic and metal lids 3-inches in diameter or larger\n\nIn garbage\n\nLoose lids less than 3-inches in diameter\nLoose plastic bottle caps\nMetal beer and soda caps\n\n\n'],
  ['\nHow to recycle\n\nBrake or Transmission Fluid\nHazardous \xe2\x80\x93 no charge\nBring brake and transmission fluids to a household hazardous waste facility:\n\nPut brake and transmission fluids in a sealed container that is 5-gallons or less.\nLimit 50-gallons per trip.\n\nFor more information, call our household hazards line at (206) 296-4692. Hours are 9 a.m. \xe2\x80\x93 4:30 p.m., Monday through Friday.\nDid you know?\nDon\xe2\x80\x99t pour brake and transmission fluids down drains or toilets, down storm drains, or into soil. These all cause water pollution.\n\n'],
  ['\nHow to recycle\n\nTrees or Brush\nIn food and yard waste\nTrees, brush, and branches go in the food and yard waste:\n\nCut down to 4 inches or less in diameter and 4 feet or less in length.\nAvoid extra charges \xe2\x80\x93 Items should fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nNext to bin\nBundle trees and brush and set next to the bin. {{proj[7].rate_text}}\n\nTie bundles with natural twine. No plastic allowed.\nBundles must be 2 feet or less in diameter.\n\nTransfer station\nBring trees and brush to city transfer stations. {{proj[1].rate_text}}\n\nAll trees, brush, or branches must be 8 feet or less in length.\nAll pieces must be 8 inches or less in diameter.\n\n\n'],
  ['\nHow to recycle\n\nBrick\nDonate\nYou can donate bricks in good condition to many building supply stores which specialize in salvaged materials.\nIn garbage\nBrick can go in the garbage if it doesn\xe2\x80\x99t exceed the weight limits printed on your bin.\nTransfer station\nBring brick to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nBubble Wrap\nIn recycling\nBundle bubble wrap together with recyclable plastic bags (such as newspaper bags, shopping bags, and dry cleaning bags) in a plastic bag.\n\n'],
  ['\nHow to recycle\n\nBuckets\nIn recycling\nClean buckets go in your recycling bin or can be set at the curb next to your bin.\n\n'],
  ['\nHow to recycle\n\nButter Boxes\nIn recycling\nClean butter boxes and other clean paper food boxes go in the recycling.\nIn garbage\nButter wrappers go in the garbage.\n\n'],
  ['\nHow to recycle\n\nButter Boxes\nIn recycling\nClean butter boxes and other clean paper food boxes go in the recycling.\nIn garbage\nButter wrappers go in the garbage.\n\n'],
  ['\nHow to recycle\n\nCan Lids\nIn recycling \xe2\x80\x93 rinse first\nKeep can lids partially attached or push the lid into the can. You don\xe2\x80\x99t need to remove the can label.\nIn garbage\nLoose can lids (not attached) go in the garbage.\n\n'],
  ['\nHow to recycle\n\nAerosol Cans\nHazardous \xe2\x80\x93 no charge\nBring cans that contain hazardous materials like paint, solvents, or other flammables to a household hazardous waste facility. No fee.\nIn garbage\n\nEmpty aerosol cans\nPartially full cans with non-hazardous contents\n\n\n'],
  ['\nHow to recycle\n\nAuto Glass\nIn garbage\nBroken auto glass can go in the garbage:\n\nGlass must fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nDrop-off locations\nBring auto glass to city transfer stations. Fees apply.\n\n'],
  ['\nHow to recycle\n\nVehicles\nDrop-off locations\nMany charitable organizations accept vehicles and provide a receipt for a tax deduction.\n\n'],
  ['\nHow to recycle\n\nCardboard Boxes\nIn recycling\nCardboard and flattened cardboard boxes go in the recycling.\nNext to bin \xe2\x80\x93 no charge\nCardboard that doesn\'t fit can go next to your bin on your recycling day. Bundle and set next to the bin, or put in a box or container next to your bin.\nThere is no charge for extra recycling.\nIn food and yard waste\nCardboard with grease or oil stains (like pizza boxes) go in the food and yard waste bin.\nPut cardboard that is mostly wet in the food and yard waste bin.\n\n'],
  ['\nHow to recycle\n\nCorrugated Cardboard\nIn recycling\nCardboard and flattened cardboard boxes go in the recycling.\nNext to bin \xe2\x80\x93 no charge\nCardboard that doesn\'t fit can go next to your bin on your recycling day. There is no charge for extra recycling.\nBundle and set next to the bin, or put in a box or container next to your bin.\nIn food and yard waste\nCardboard with grease or oil stains (like pizza boxes) go in the food and yard waste bin.\nPut cardboard that is mostly wet in the food and yard waste bin.\n\n'],
  ['\nHow to recycle\n\nSoiled or Greasy Cardboard\nIn food and yard waste\nCardboard with food grease or oil stains (like pizza boxes) go in the food and yard waste.\nPut cardboard that is mostly wet in the food and yard waste.\n\n'],
  ['\nHow to recycle\n\nWaxed Cardboard\nIn food and yard waste\nFlattened waxed cardboard boxes, such as large produce boxes, go in the food and yard waste.\nPaperboard boxes (like butter and cereal boxes) go in the recycling. They aren\xe2\x80\x99t true waxed cardboard. The shiny coating on these boxes is a thin layer of plastic.\n\n'],
  ['\nHow to recycle\n\nCarpet or Padding\nIn garbage\nCarpet and padding can go in the garbage. Cut into smaller pieces if carpet or padding doesn\xe2\x80\x99t fit in your bin with the lid closed.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item pickup. {{proj[4].rate_text}}\nTransfer station\nBring carpet and padding up to 8 feet long and 200 pounds to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nCast Iron\nMetal parts larger than 3-inches go in the recycling.\nIn recycling\n\nRusted metal can be recycled unless the metal is falling apart.\nSmall amounts of plastic, wood, or rubber can be attached.\n\nNext to bin \xe2\x80\x93 no charge\nLarge metal parts can be put at the curb for pickup on your recycling collection day.\n\nThese must be bundled or tied.\nThe maximum size is 2-feet on all sides.\n\nIn garbage\n\nMetal items with large amounts of plastic, wood, or rubber attached\nMetal items that are smaller than 3-inches\n\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item collection. Fees apply.\nDrop-off locations\nAll metal, except car parts, is accepted as recycling at city transfer stations. There is no charge for recycling at the transfer station.\n\nAll metal, except car parts, is accepted as recycling at city transfer stations. There is no charge for recycling at the transfer station.\nMaximum size is 8-feet long.\nThere is a charge for appliances, limit 2 per load.\n\n\n'],
  ['\nHow to recycle\n\nCD or DVD Cases\nIn garbage\nCD and DVD cases can go in the garbage.\nDrop-off locations\nStores that sell used CDs or DVDs may take cases in good condition.\n\n'],
  ['\nHow to recycle\n\nCDs, DVDs, or Floppies\nDonate and reuseDonate CDs and DVDs in good condition to local thrift stores.\nResell or give away usable CDs and DVDs through sites like Craigslist, Freecycle, and Buy Nothing.\nIn garbage\n\nCDs\nDVDs\nFloppy discs\nCD and DVD cases\n\n\n'],
  ['\nHow to recycle\n\nCell Phones\nDonate and reuseDonate working cell phones to local thrift stores or recycle cellphones via the Take It Back Network.\nResell or give working cell phones through sites like Craigslist, Freecycle, and Buy Nothing.\n\n'],
  ['\nHow to recycle\n\nCell Phone Batteries\nDonate\nFind drop off and mail back recycling options at Call2Recycle outlet.\nHazardous \xe2\x80\x93 no charge\nBring rechargeable and lithium-ion batteries to a household hazardous waste facility. No fee.\nThey can\xe2\x80\x99t go in the garbage.\n\n'],
  ['\nHow to recycle\n\nCereal or Cracker Boxes\nIn recycling\nEmpty cereal and cracker boxes go in the recycling.\nIn garbage\nPlastic liners and trays from food boxes go in the garbage.\n\n'],
  ['\nHow to recycle\n\nChild Car Seats\nDonate and reuse\nDonate car seats in good condition to local thrift stores.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nIn garbage\nOld and expired child car seats go in the garbage.\nDid you know?\nDon\xe2\x80\x99t reuse broken car seats or car seats that have been in accidents. It isn\xe2\x80\x99t safe.\n\n'],
  ['\nHow to recycle\n\nChip Bags\nIn garbage\nChip bags go in the garbage because they are made from several different materials that can\xe2\x80\x99t be separated for recycling.\n\n'],
  ['\nHow to recycle\n\nHoliday Lights\nIn garbage\nChristmas and holiday lights can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nChristmas Trees\nNext to bin\nFrom 12/26/17 - 1/31/18, holiday trees, wreaths, and greens can be composted for free. Place on the curb next to your food and yard waste cart on your regular collection day.\n\nFlocked and plastic trees or wreaths will be charged as extra garbage.\nRemove all decorations and lights, tinsel, metal clips, ornaments and bows.\nTrees must be cut into lengths to 4-feet or shorter.\nBundle each section with sisal string or twine (not plastic).\n\nAt apartments \xe2\x80\x93 One tree may be placed next to each food and yard waste cart at no extra charge each collection day.\nDrop-off locations\nFrom 12/26/17 - 1/31/18, bring Christmas trees to city transfer stations for free. Starting 2/1/18, regular fees apply.\n\nTrees should not exceed 8-feet in length and must be free of decoration.\nTrunks should not exceed 4-inches in diameter.\nThe stations will accept up to 3 trees per vehicle.\n\n\n'],
  ['\nHow to recycle\n\nClamshell Containers\nIn recycling \xe2\x80\x93 rinse first\n\nPlastic clamshell containers\nPlastic-coated (shiny) clamshell containers\nClean paper clamshell containers\n\nIn food and yard waste\n\nClamshell containers marked \xe2\x80\x9cCompostable\xe2\x80\x9d or \xe2\x80\x9c#7 PLA\xe2\x80\x9d\nDirty paper clamshell containers without a plastic coating\n\nIn garbage\n\nStyrofoam clamshell containers\nDirty plastic or plastic-coated (shiny) clamshell containers\n\n\n'],
  ['\nHow to recycle\n\nDirt or Soil\nIn garbage\nSoil can go in your garbage if it doesn\xe2\x80\x99t exceed the weight limits printed on your bin.\nTransfer station\nBring soil to city transfer stations. {{proj[8].rate_text}}\n\n'],
  ['\nHow to recycle\n\nCleaning Supplies\nHazardous \xe2\x80\x93 no charge\nBring partially full containers of cleaning supplies labeled with caution, warning, danger, or poison to a household hazardous waste facility. No fee.\n\nAll containers must be 5-gallons or less.\nLimit 50-gallons per trip.\n\nIn recycling \xe2\x80\x93 rinse first\nEmpty non-toxic cleaning supply containers go in the recycling.\n\n'],
  ['\nHow to recycle\n\nClock Radios\nDonate and reuse\nDonate working clock radios to local thrift stores.\nResell or give them away using sites like Craigslist, Freecycle, and Buy Nothing.\nIn garbage\nClock radios go in the garbage.\n\n'],
  ['\nHow to recycle\n\nClothes or Shoes\nIn garbage\nClothes and shoes can go in the garbage.\nDrop-off locations\nStained, worn out, ripped, or damaged clothing and shoes can be turned into new products through Threadcycle. Some local thrift and second-hand stores are partners and will accept these items at their regular collection or drop box locations.\n\n'],
  ['\nHow to recycle\n\nCoffee Filters\nIn food and yard waste\nPaper coffee filters are compostable and go in the food and yard waste together with coffee grounds.\nIn garbage\nPlastic, plastic-coated, or cloth coffee filters go in the garbage.\n\n'],
  ['\nHow to recycle\n\nCompostable Food Service Items\nIn food and yard waste\nFood service items labeled \xe2\x80\x9cCompostable\xe2\x80\x9d or \xe2\x80\x9c#7 PLA\xe2\x80\x9d go in the food and yard waste. This includes:\n\nFood containers\nCups\nPlates\nStraws and utensils\nPaper napkins\nPaper towels\nUncoated (not shiny) paper plates and bowls (such as Chinet brand)\n\nLearn more about compostable packaging (pdf).\n\n'],
  ['\nHow to recycle\n\nComputers & Laptops\nDrop-off locations\nFind locations to recycle computers and laptops via the Take It Back Network.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. Fees apply.\nDid you know?\nComputers and laptops can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\nComputer Batteries\nHazardous \xe2\x80\x93 no charge\nBring rechargeable and lithium-ion batteries to a household hazardous waste facility. No fee.\nThey can\xe2\x80\x99t go in the garbage.\n\n'],
  ['\nHow to recycle\n\nComputers Monitors\nDrop-off locations\nFind locations to recycle computer monitors via the Take It Back Network.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. Fees apply.\nDid you know?\nMonitors can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\nConcrete or Asphalt\nIn garbage\nConcrete and asphalt can go in the garbage if it doesn\xe2\x80\x99t exceed the weight limits, and fits in your bin with the lid closed. Each concrete or asphalt piece must be less than 2 cubic feet.\nTransfer station\nBring concrete and asphalt to city transfer stations. {{proj[0].rate_text}}\n\nEach concrete or asphalt piece must be less than 2\' x 2\' x 2\' and less than 200 lbs.\n\n\n'],
  ['\nHow to recycle\n\nMixed C & D\nTransfer station\nBring mixed construction and demolition waste to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nContaminated Dirt or Soil\nIn garbage\nDirt contaminated with non-hazardous materials like plastic, wood, or metal can go in the garbage if it doesn\xe2\x80\x99t exceed the weight limits printed on your bin.\nTransfer station\nBring dirt contaminated with non-hazardous materials like plastic, wood, or metal to city transfer stations. {{proj[0].rate_text}}\nHazardous\nFor dirt that contains hazardous materials, call the household hazards line at (206) 296-4692. Hours are 9 a.m. \xe2\x80\x93 4:30 p.m., Monday through Friday.\n\n'],
  ['\nHow to recycle\n\nCooking Oil\nRecycle, next to bin \xe2\x80\x93 no charge\nYou can recycle up to 2 gallons of cooking oil on each recycling collection day:\n\nPour cooled oil into a 1-gallon plastic container with a tight-fitting, screw-on lid.\nLabel the container with your name and address.\nSet up to 2 labeled 1-gallon containers on the curb next to your recycling bin.\nApartment / Condo residents: Set out up to 2 labeled 1-gallon containers per cart at your building/complex.\n\nIn garbage\nPut cooking oil in a closed container that will keep the oil contained, such as a Ziploc bag, or in a thick plastic bag that\xe2\x80\x99s tightly tied.\n\n'],
  ['\nHow to recycle\n\nCopiers & Fax Machines\nDonate and reuseFind locations to recycle copiers and fax machines via the Take It Back Network (fees may apply).\nResell or give away working copiers and fax machines using sites like Craigslist, Freecycle, and Buy Nothing.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. {{proj[6].rate_text}}\nDid you know?\nCopiers and fax machines can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\nCopper, Bronze or Brass\nIn recycling\nMetal parts larger than 3-inches go in the recycling.\n\nSmall amounts of plastic, wood, or rubber can be attached.\n\nNext to bin \xe2\x80\x93 no charge\nLarge metal parts can be put at the curb for pickup on your recycling collection day.\n\nThese must be bundled or tied.\nThe maximum size is 2-feet on all sides.\n\nIn garbage\n\nMetal items with large amounts of plastic, wood, or rubber attached\nMetal items that are smaller than 3-inches\n\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item collection. Fees apply.\nDrop-off locations\nAll metal, except car parts, is accepted as recycling at city transfer stations. There is no fee for most metal.\n\nMaximum size is 8-feet long.\nThere is a charge for appliances, limit 2 per load.\n\n\n'],
  ['\nHow to recycle\n\nCorks\nIn garbage\nCorks go in the garbage. They are too dense to compost or recycle.\nDrop-off locations\nCorks can also be recycled through the Cork ReHarvest Program, which has drop boxes at PCC, Whole Foods Markets, and Wine World Warehouses.\n\n'],
  ['\nHow to recycle\n\nStyrofoam Cups\nIn garbage\nStyrofoam cups go in the garbage.\n\n'],
  ['\nHow to recycle\n\nDirt or Soil\nIn garbage\nSoil can go in your garbage if it doesn\xe2\x80\x99t exceed the weight limits printed on your bin.\nTransfer station\nBring soil to city transfer stations. {{proj[8].rate_text}}\n\n'],
  ['\nHow to recycle\n\nDisposable Diapers\nIn garbage\nPut all disposable (even if marked "compostable") diapers in a bag, tie off, and place in garbage.\n\n'],
  ['\nHow to recycle\n\nDrinking Glasses\nIn garbage\nDrinking glasses can go in the garbage, whether they\xe2\x80\x99re broken or not.\nDid you know?\nDrinking glasses can\xe2\x80\x99t be recycled by Seattle because they have different melting points than recyclable glass.\n\n'],
  ['\nHow to recycle\n\nBarrels or Drums\nHazardous\nSealed drums and drums that held hazardous waste must go to King County Household Hazardous Waste.\nDrop-off locations\nBring barrels and drums that held non-hazardous material to city transfer stations:\n\nEmpty barrels and drums must be clean and cut in half.\nClean metal can be recycled for no fee.\n\nIn garbage\nPlastic and dirty metal drums that held non-hazardous material can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nDrywall\nIn garbage\nDrywall can go in the garbage. Break drywall down so it fits in your bin with the lid closed and does not exceed weight limits.\nTransfer station\nBring drywall to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nDry Cleaner Bags\nIn recycling\nBundle dry cleaner bags together with other recyclable plastic bags (such as newspaper bags or grocery bags). Put bundle into one plastic bag, tie off, and put in the recycling.\nIn garbage\nSingle dry cleaner bags go in the garbage.\nDid you know?\nSingle plastic bags go in the garbage because they jam the machinery at the recycling facility.\n\n'],
  ['\nHow to recycle\n\nDucts, Furnace Parts and Fireplace Inserts\nHazardous\nTo dispose duct work, fire place inserts, or other materials - that contains asbestos, contact the Puget Sound Clean Air Agency at (206) 343-8800.\nDrop-off locations\nMany scrap metal dealers will buy asbestos-free metal duct, fireplace inserts and furnace parts.\nDid you know?\nDuct work, fireplace inserts and furnace parts are not accepted at city transfer stations.\n\n'],
  ['\nHow to recycle\n\nFoam Egg Cartons\nIn garbage\nFoam egg cartons go in the garbage.\nDid you know?\nMany egg sellers at farmers markets will take back clean egg cartons to reuse them.\n\n'],
  ['\nHow to recycle\n\nPaper Egg Cartons\nIn recycling\n\nClean paper egg cartons\n\nIn food and yard waste\n\nPaper egg cartons with food residue on them\n\nDid you know?\nMany egg sellers at farmers\' markets will take back clean egg cartons to reuse them.\n\n'],
  ['\nHow to recycle\n\nEngines, Motors or Car Parts\nIn garbage\nCar parts 3-inches or smaller on any side can go in the garbage.\nDrop-off locations\nMany scrap metal dealers will buy car parts.\nDid you know?\nCar parts aren\xe2\x80\x99t accepted for recycling because they contain grease, which contaminates other recyclable items.\n\n'],
  ['\nHow to recycle\n\nEnvelopes\nIn recycling\nRecycle all paper envelopes, including those with plastic windows.\nIn garbage\nBubble pack envelopes go in the garbage.\nDid you know?\nThis recyclable item is banned from Seattle\'s garbage.\n\n'],
  ['\nHow to recycle\n\nE-waste\nDrop-off locations\nFind locations to recycle the following electronics via the Take It Back Network (fees may apply):\n\nTVs (size limits apply)\nMonitors\nCPUs\nE-readers (like Kindle or NOOK)\nComputers and laptops\nTablets\nPortable DVD players\n\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. Fees apply.\nDid you know?\nElectronics can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\nEyeglass Frames\nIn garbage\nEyeglass frames can go in the garbage.\nDrop-off locations\nYou can donate eyeglass frames to The Lions Club or organizations affiliated with OneSight.\n\n'],
  ['\nHow to recycle\n\nEyeglasses\nIn garbage\nEyeglasses can go in the garbage.\nDrop-off locations\nYou can donate eyeglasses to The Lions Club or organizations affiliated with OneSight.\n\n'],
  ['\nHow to recycle\n\nFabric or Textiles\nDonate\nStained, worn out, ripped, or damaged fabric or textiles can be turned into new products through Threadcycle. Some local thrift and second-hand stores are partners and will accept these items at their regular collection or drop box locations.\nIn garbage\nFabric and textiles can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nKleenex, Facial Tissue\nIn garbage\nKleenex (facial tissue) goes in the garbage.\n\n'],
  ['\nHow to recycle\n\nFats, Oils, or Grease\nIn garbage\nPut fats, oil, or grease in a closed container, Ziploc bag, or in a thick plastic bag that\xe2\x80\x99s tightly tied.\nDid you know?\nFats, oils, and grease shouldn\xe2\x80\x99t be poured down the drain because they clog pipes and create backups.\n\n'],
  ['\nHow to recycle\n\nCopiers & Fax Machines\nDonate and reuseFind locations to recycle copiers and fax machines via the Take It Back Network (fees may apply).\nResell or give away working copiers and fax machines using sites like Craigslist, Freecycle, and Buy Nothing.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. {{proj[6].rate_text}}\nDid you know?\nCopiers and fax machines can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\nFiberglass\nCaution: Fiberglass can irritate your skin and eyes. Wear gloves, googles, and protective clothing when handling.\nIn garbage\nFiberglass can go in the garbage:\n\nItems must fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nDrop-off locations\nBring fiberglass to city transfer stations. Fees apply.\n\n'],
  ['\nHow to recycle\n\nFire Extinguishers\nIn garbage\nEmpty CO2 and halon (bromo difluoromethane) fire extinguishers go in the garbage.\nHazardous \xe2\x80\x93 no charge\nBring fire extinguishers that are full or partially full to a household hazardous waste facility. No fee.\n\n'],
  ['\nHow to recycle\n\nFlares\nDrop-off locations\nBring flares that don\xe2\x80\x99t contain an explosive charge to a household hazardous waste facility. No fee.\nHazardous\nFor flares with an explosive charge, call the Seattle Police Firing Range at (206) 684-7470.\n\n'],
  ['\nHow to recycle\n\nFluorescent Light Bulbs\nHazardous \xe2\x80\x93 no charge\nBring up to 10 fluorescent tubes and CFLs per a trip to a household hazardous waste facility or to a LightRecycle location. No fee.\nDid you know?\nFluorescent tubes and CFLs are banned from the garbage because they contain mercury, which is highly toxic. To prevent breaking the tubes or bulbs and releasing mercury when storing or transporting, wrap them in newspaper or put back in their original packaging.\n\n'],
  ['\nHow to recycle\n\nFlushable Wipes\nIn garbage\nBaby wipes, wet wipes, cleaning wipes, and any wipes labeled \xe2\x80\x9cflushable\xe2\x80\x9d go in your garbage.\nIf flushed down your toilet, they can clog your sewer pipes.\n\n'],
  ['\nHow to recycle\n\nStyrofoam Blocks or Packing Sheets\nIn garbage\nStyrofoam blocks and packing sheets go in the garbage.\nDrop-off locations\nStyro Recycle in Kent accepts Styrofoam blocks, packing sheets, and packing peanuts for recycling.\n\n'],
  ['\nHow to recycle\n\nFoamcore\nIn garbage\nFoamcore and foam boards go in the garbage.\n\n'],
  ['\nHow to recycle\n\nFoil Pie Pans\nIn recycling \xe2\x80\x93 rinse first\n\nAluminum food pans\nAluminum foil \xe2\x80\x93 don\xe2\x80\x99t crumple into a ball\n\nIn garbage\n\nDirty or food-covered aluminum foil or food pans\n\n\n'],
  ['\nHow to recycle\n\nFood Box Liners\nIn garbage\nPlastic liners, bags, and trays from food boxes go in the garbage.\n\n'],
  ['\nHow to recycle\n\nMeat or Food Trays\nIn food and yard waste\nBrown or beige trays for meat, poultry, and fish go in the food and yard waste.\nIn garbage\nStyrofoam meat trays and the plastic absorbent insert go in the garbage.\nDid you know?\nBrown or beige trays for meat, poultry, and fish are made from plant-based material and are compostable.\n\n'],
  ['\nHow to recycle\n\nFood Scraps\nIn food and yard waste\n\nFruit and vegetables\nBread, pasta, rice, and grains\nEggshells and nutshells\nCoffee grounds and filters\nTea bags\nMeat, fish, and chicken\nDairy products like milk, butter, and cheese\nBones and seafood shells\nCompostable (uncoated) paper such as paper napkins, paper towels, and pizza boxes\n\n\n'],
  ['\nHow to recycle\n\nFrozen Food Boxes\nIn recycling\nClean frozen food boxes and other food boxes go in the recycling.\n\n'],
  ['\nHow to recycle\n\nFurnaces\nHazardous\nTo dispose furnaces, furnace parts, or boilers that contain asbestos, contact the Puget Sound Clean Air Agency at (206) 343-8800.\nDid you know?\nMany scrap metal dealers will buy asbestos-free metal duct and furnace parts.\n\n'],
  ['\nHow to recycle\n\nSmall Gas Canisters\nDrop-off locations\nEmpty small backpacking-style isobutane fuel canisters (excluding green \xe2\x80\x9cColeman\xe2\x80\x9d style propane canisters) can be dropped off for free at the MSR Repair Shop, in SODO, or at the Mountaineers Bookstore, in NE Seattle.\nEmpty small \xe2\x80\x9cColeman\xe2\x80\x9d style canisters can be dropped off at a Recology Store. For more information visit recology.com/store or email store@recology.com. Limits and fees may apply.\nHazardous \xe2\x80\x93 no charge\nSmall gas canisters with any amount of gas or butane must be taken to a household hazardous waste facility. No fee.\nIn garbage\nEmpty butane and gas canisters under 2-pounds can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nGas Cans\nIn garbage\nEmpty gas cans that are 5-gallons or smaller can go in the garbage. Leave lid off empty can for 2 days before putting in garbage to release gas fumes.\n\n'],
  ['\nHow to recycle\n\nGasoline\nHazardous \xe2\x80\x93 no charge\nBring gasoline to a household hazardous waste facility:\n\nPut gas in a sealed container that is 5-gallons or less.\nUse gasoline-compatible containers (not food or milk jugs).\nLimit 30-gallons per trip.\n\n\n'],
  ['\nHow to recycle\n\nGift Wrap\nIn recycling\n\nWrapping paper\nPaper gift bags\nPaper gift boxes\nGift tissue paper\n\nIn garbage\n\nPlastic gift wrap\nFoil gift wrap\nPlastic or foil gift bows\n\n\n'],
  ['\nHow to recycle\n\nGlass Bottles or Jars\nIn recycling \xe2\x80\x93 rinse first\n\nGlass bottles and jars\nLids 3-inches or larger\nLids smaller than 3-inches can be recycled only if attached to the bottle or jar.\n\nDid you know?\nJars coated with oily food like peanut butter can be wiped first with a paper towel (put the paper towel in the food and yard waste). Very small amounts of peanut butter or food residue are okay.\n\n'],
  ['\nHow to recycle\n\nBroken Glass\nIn recycling\n\nBroken bottles and jars 3-inches or larger.\n\nIn garbage\n\nAll pieces of broken drinking glasses or wine glasses.\nPieces of broken bottles and jars smaller than 3-inches.\n\n\n'],
  ['\nHow to recycle\n\nGlass or Ceramic Household Items\nDonate and reuse\nDonate glass or ceramic household items in good condition to local thrift stores.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nIn garbage\nDamaged glass or ceramic household items such as plates, bowls, or drinking glasses can go in the garbage.\nDid you know?\nThese items can\xe2\x80\x99t be recycled by Seattle because they have different melting points than recyclable glass.\n\n'],
  ['\nHow to recycle\n\nGold, Silver, Etc.\nIn garbage\nYou can put gold, silver, and other precious metals in the garbage.\nDrop-off locations\nYou can often sell gold, silver, and broken jewelry to jewelry buyers or coin and precious metal dealers.\n\n'],
  ['\nHow to recycle\n\nGlues or Adhesives\nHazardous \xe2\x80\x93 no charge\nBring glues and adhesives labeled with caution, warning, danger, or poison to a household hazardous waste facility. No fee.\n\nAll containers must be 5-gallons or less.\nLimit 50-gallons per trip.\n\nIn garbage\nNon-toxic glues go in the garbage. This includes Elmer\xe2\x80\x99s, glue sticks, and other glues used in schools.\n\n'],
  ['\nHow to recycle\n\nGrass Clippings or Sod\nIn food and yard waste\nGrass clippings and small amounts of sod can go in the food and yard waste. Don\xe2\x80\x99t exceed the weight limits printed on your bin.\nDrop-off locations\nBring large amounts of grass clippings and sod to city transfer stations. Fees apply.\n\n'],
  ['\nHow to recycle\n\nGreeting Cards\nIn recycling\nGreeting cards and other paper cards go in the recycling.\n\n'],
  ['\nHow to recycle\n\nGrocery or Shopping Bags\nIn recycling\n\nClean and empty plastic grocery bags \xe2\x80\x93 bundle into one bag and tie off\nClean and dry paper bags or paper sacks\n\nIn food and yard waste\n\nPaper bags that are wet or food-soiled\n\nIn garbage\n\nPlastic bags that are wet or food-soiled\nPlastic produce bags\nSingle plastic bags\n\nDid you know?\nSingle plastic bags go in the garbage because they jam the machinery at the recycling facility. Produce bags are not recyclable because they often contain food or moisture that contaminate the recycling.\n\n'],
  ['\nHow to recycle\n\nGutters\nTransfer station\nBring gutters 8 feet or less in length to city transfer stations:\n\nFees apply for plastic gutters.\nThere is no fee for aluminum gutters.\n\n\n'],
  ['\nHow to recycle\n\nHand Tools\nDonate and reuse\nDonate hand tools in good condition to local thrift stores.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nIn recycling\n\nMetal tools 3 inches or more in size\nCan include small amounts of wood, rubber, or plastic\n\nIn garbage\n\nMetal tools less than 3 inches\nTools that contain large amounts of rubber, wood, or plastic\n\n\n'],
  ['\nHow to recycle\n\nHearing Aid Batteries\nIn garbage\nHearing aid batteries can go in the garbage.\nDrop-off locations\nSome locations that sell hearing aid batteries will take them back for recycling.\n\n'],
  ['\nHow to recycle\n\nHelium Tanks\nIn garbage\nEmpty helium tanks 5-gallons or smaller can go in the garbage:\n\nTurn the valve all the way to the left to release remaining helium.\nAvoid extra charges \xe2\x80\x93 Tank should fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nDrop-off locations\nCheck with your supplier for return and refill options.\nFor tanks larger than 5-gallons or commercial cylinders, refer to information printed on the tank for instructions on recycling or exchange options.\n\n'],
  ['\nHow to recycle\n\nHobby Chemicals\nHazardous \xe2\x80\x93 no charge\nBring partially full containers of hobby chemicals labeled with caution, warning, danger, or poison to a household hazardous waste facility. No fee.\n\nAll containers must be 5-gallons or less.\nLimit 50-gallons per trip.\n\nIn garbage\nEmpty hobby chemical containers go in the garbage.\n\n'],
  ['\nHow to recycle\n\nHot Cups or Coffee Cups\nIn recycling \xe2\x80\x93 rinse first\n\nPaper coffee cups with a small amount of liquid\n\nIn food and yard waste\n\nHot or coffee cups labeled as \xe2\x80\x9cCompostable\xe2\x80\x9d\n\nIn garbage\n\nStyrofoam coffee cups\n\n\n'],
  ['\nHow to recycle\n\nHouse Plants\nIn food and yard waste\nHouse plants go in the food and yard waste. Remove plants from potting soil and planters.\n\n'],
  ['\nHow to recycle\n\nAlkaline Batteries\nDrop-off locations\nBring alkaline batteries to city transfer stations. No fee.\nBring alkaline batteries to a household hazardous waste facility where the materials in the batteries will be reclaimed and recycled. No fee.\nIn garbage\nNon-rechargeable, household alkaline batteries (such as AAA, AA, C, D, or 9-volt) can go in the garbage.\nHousehold hazardous waste facility\nBring alkaline batteries and rechargeable batteries to a household hazardous waste facility, where the materials in the batteries will be reclaimed and recycled. No fee.\n\n'],
  ['\nHow to recycle\n\nHousehold Furniture\nDonate and reuse\nDonate furniture in good condition to local thrift stores.\nResell or give away using sites like Craigslist, Freecycle, and Buy Nothing.\nIn garbage\nFurniture can go in the garbage. Break furniture down so it fits in your bin with the lid closed.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item pickup. {{proj[6].rate_text}}\nTransfer station\nYou can also bring furniture to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nIce Cream Cartons\nIn recycling \xe2\x80\x93 rinse first\nIce cream cartons and lids go in the recycling.\n\n'],
  ['\nHow to recycle\n\nIncandescent Light Bulbs\nIn garbage\nUnbroken incandescent light bulbs go in your garbage.\n\n'],
  ['\nHow to recycle\n\nIron or Steel\nIn recycling\nMetal parts larger than 3-inches go in the recycling.\n\nSmall amounts of plastic, wood, or rubber can be attached.\nRusted metal can be recycled unless the metal is falling apart.\n\nNext to bin \xe2\x80\x93 no charge\nLarge metal parts can be put at the curb for pickup on your recycling collection day.\n\nThese must be bundled or tied.\nThe maximum size is 2-feet on all sides.\n\nIn garbage\n\nMetal items with large amounts of plastic, wood, or rubber attached.\nMetal items that are smaller than 3-inches.\n\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item collection. Fees apply.\nDrop-off locations\nAll metal, except car parts, is accepted as recycling at city transfer stations. There is no fee for most metal.\n\nMaximum size is 8-feet long.\nThere is a charge for appliances, limit 2 per load.\n\n\n'],
  ['\nHow to recycle\n\nBottle Caps or Jar Lids\nIn recycling\n\nSmall plastic bottle caps if screwed onto an empty plastic bottle\nLoose plastic and metal lids 3-inches in diameter or larger\n\nIn garbage\n\nLoose lids less than 3-inches in diameter\nLoose plastic bottle caps\nMetal beer and soda caps\n\n\n'],
  ['\nHow to recycle\n\nJewelry or Coins\nIn garbage\nYou can put jewelry and coins in the garbage.\nDrop-off locations\nYou can donate jewelry and coins to thrift stores, and can often sell these items to jewelry buyers or coin and precious metal dealers.\n\n'],
  ['\nHow to recycle\n\nJuice Boxes & Cartons\nIn recycling \xe2\x80\x93 rinse first\nPlastic spouts don\xe2\x80\x99t need to be removed to recycle juice boxes and cartons.\n\n'],
  ['\nHow to recycle\n\nMilk Cartons\nIn recycling \xe2\x80\x93 rinse first\nPlastic spouts don\xe2\x80\x99t need to be removed to recycle milk cartons.\n\n'],
  ['\nHow to recycle\n\nPlastic Milk or Juice Jugs\nIn recycling \xe2\x80\x93 rinse first\nEmpty milk and juice jugs and bottles go in the recycling.\nPlastic lids and caps can be recycled if attached to the bottle.\n\n'],
  ['\nHow to recycle\n\nJunk Mail\nIn recycling\nAll paper junk mail goes in the recycling. This includes:\n\nCatalogs\nFliers\nEnvelopes \xe2\x80\x93 with or without clear plastic windows\nNewspapers\nPhone books\n\nDid you know?\nPaper and junk mail can\xe2\x80\x99t go in the garbage.\n\n'],
  ['\nHow to recycle\n\nKeys\nIn garbage\nKeys and other metal items smaller than 3-inches go in the garbage.\nDid you know?\nSmall metal items can fall through the sorting machinery at the recycling plant.\n\n'],
  ['\nHow to recycle\n\nKeys\nIn garbage\nKeys and other metal items smaller than 3-inches go in the garbage.\nDid you know?\nSmall metal items can fall through the sorting machinery at the recycling plant.\n\n'],
  ['\nHow to recycle\n\nComputers & Laptops\nDrop-off locations\nFind locations to recycle computers and laptops via the Take It Back Network.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. Fees apply.\nDid you know?\nComputers and laptops can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\nLaundry Detergent Boxes\nIn recycling\nEmpty and flatten laundry detergent boxes and then put in the recycling.\n\n'],
  ['\nHow to recycle\n\nLaundry Detergent Jugs\nIn recycling\n\nPlastic laundry detergent jugs\nCaps screwed onto the bottle\n\nIn garbage\n\nLoose caps\n\n\n'],
  ['\nHow to recycle\n\nLawn Mowers or Power Equipment\nDonate\nDonate lawn mowers or power equipment in working condition to local thrift stores. Call first to confirm acceptance policies.\nTransfer station\nYou must drain all gas and oil from lawn mowers and other power equipment. Bring emptied mowers and equipment to city transfer stations. No charge for lawn mowers.\nHazardous \xe2\x80\x93 no charge\nBring gas and oil to a household hazardous waste facility. No fee.\n\nDon\xe2\x80\x99t mix fluids together!\nPut fluids in a sealed container that is 5 gallons or less.\nLimit 50 gallons per trip.\n\n\n'],
  ['\nHow to recycle\n\nLead\nCaution: Protect your skin when handling lead. It\xe2\x80\x99s potentially hazardous.\nIn recycling\nLead pieces 3-inches or larger can go in the recycling:\n\nLead should fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nDrop-off locations\nBring lead 8-feet or smaller to city transfer stations. Fees apply.\n\n'],
  ['\nHow to recycle\n\nLeaves or Non-Woody Yard Waste\nIn food and yard waste\nLeaves and non-woody yard waste go in the food and yard waste.\n\nItems must fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nDrop-off locations\nBring leaves or non-woody yard waste to city transfer stations. Fees apply.\n\n'],
  ['\nHow to recycle\n\nPlastic Lids\nIn recycling\nLids 3-inches in diameter or larger go in the recycling. This includes:\n\nYogurt container lids\nMargarine tub lids\nDeli container lids\nCold and hot drink cup lids\nSmall plastic caps if screwed onto an empty plastic bottle\n\nIn garbage\n\nLids less than 3-inches in diameter\nLoose plastic bottle caps\n\n\n'],
  ['\nHow to recycle\n\nFluorescent Light Bulbs\nHazardous \xe2\x80\x93 no charge\nBring up to 10 fluorescent tubes and CFLs per a trip to a household hazardous waste facility or to a LightRecycle location. No fee.\nDid you know?\nFluorescent tubes and CFLs are banned from the garbage because they contain mercury, which is highly toxic. To prevent breaking the tubes or bulbs and releasing mercury when storing or transporting, wrap them in newspaper or put back in their original packaging.\n\n'],
  ['\nHow to recycle\n\nIncandescent Light Bulbs\nIn garbage\nUnbroken incandescent light bulbs go in your garbage.\n\n'],
  ['\nHow to recycle\n\nLED Light Bulbs\nIn garbage\nLED light bulbs go in the garbage.\n\n'],
  ['\nHow to recycle\n\nHoliday Lights\nIn garbage\nChristmas and holiday lights can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nLumber or Boards\nIn food and yard waste\nUnpainted and untreated wood goes in the food and yard waste:\n\nAll pieces must be less than 4 inches in diameter and under 4 feet long.\nRemove nails and all other non-wood materials.\nBreak lumber and boards down so they fit in your bin with the lid closed.\nDo not exceed weight limits posted on your cart.\n\nIn garbage\nPainted or treated wood goes in the garbage:\n\nAll pieces must be less than 4 inches in diameter and under 4 feet long.\nBreak lumber and boards down so they fit in your bin with the lid closed.\nDo not exceed weight limits.\n\nNext to bin\nLumber or boards which do not fit in your bin with the lid closed may be put in a plastic bag and placed next to your garbage bin on collection day. {{proj[4].rate_text}}\nTransfer station\nBring lumber and wood boards to city transfer stations. {{proj[1].rate_text}}\n\n'],
  ['\nHow to recycle\n\nMagazines\nIn recycling\nMagazines go in the recycling.\n\n'],
  ['\nHow to recycle\n\nMattresses or Futons\nDonate\nDonate futon frames in good condition to local thrift stores.  Mattresses and futons are generally not accepted at thrift stores.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item pickup. {{proj[6].rate_text}}\nTransfer station\nBring mattresses and futons to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nMeat or Food Trays\nIn food and yard waste\nBrown or beige trays for meat, poultry, and fish go in the food and yard waste.\nIn garbage\nStyrofoam meat trays and the plastic absorbent insert go in the garbage.\nDid you know?\nBrown or beige trays for meat, poultry, and fish are made from plant-based material and are compostable.\n\n'],
  ['\nHow to recycle\n\nMedicines\nDrop-off locations\nBring medicines to a secure medicine return site.\nDid you know?\nFlushing medicine down the toilet or sink, or putting medicine in your backyard compost or food and yard waste bin can pollute our waterways and the environment.\n\n'],
  ['\nHow to recycle\n\nThermometers or Mercury Items\nCaution: Mercury can greatly harm your nervous, digestive, and respiratory systems. Don\xe2\x80\x99t handle mercury directly, and try to avoid breaking items that contain mercury.\nHazardous \xe2\x80\x93 no charge\nMercury items can\xe2\x80\x99t go in the garbage. Bring thermometers, thermostats, and other items containing mercury to a household hazardous waste facility. No fee.\n\n'],
  ['\nHow to recycle\n\nMicrowaves\nDonate and reuse\nDonate microwaves in working condition to local thrift stores.\nFind locations to recycle damaged microwaves via the Take It Back Network.\nIn garbage\nSmall microwaves can go in the garbage.\nDrop-off locations\nBring microwaves to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nMilk Cartons\nIn recycling \xe2\x80\x93 rinse first\nPlastic spouts don\xe2\x80\x99t need to be removed to recycle milk cartons.\n\n'],
  ['\nHow to recycle\n\nMirrors\nDonate and reuse\nDonate mirrors in working condition to local thrift stores.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nSome building supply or second use stores accept mirrors.\nIn garbage\nMirrors can go in the garbage:\n\nItems must fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\n\n'],
  ['\nHow to recycle\n\nMotor Oil\nNext to bin \xe2\x80\x93 no charge\nYou can recycle up to 2 gallons of motor oil on each recycling collection day:\n\nPour cooled oil into a 1-gallon plastic container with a tight-fitting, screw-on lid.\nLabel the container with your name and address.\nSet up to 2 labeled 1-gallon containers on the curb next to your recycling bin.\nApartment / Condo residents: Set out up to 2 labeled 1-gallon containers per cart at your building/complex.\n\nTransfer station\nBring up to 5 gallons of oil per a trip to city transfer stations. No fee.\nHazardous \xe2\x80\x93 no charge\nBring contaminated oil that contains solvents, bleach, or other materials to a household hazardous waste facility. No fee.\nDid you know?\nMotor oil can be recycled if it doesn\xe2\x80\x99t contain solvents, bleach, or other materials.\nNever pour motor oil on the ground or down the drain; it can pollute our waterways and the environment.\n\n'],
  ['\nHow to recycle\n\nMotor Oil Containers\nIn garbage\nEmpty motor oil containers go in the garbage. They can\xe2\x80\x99t be recycled.\nDrop-off locations\nBring partially full motor oil containers to:\n\nCity transfer stations. Fees apply.\nA household hazardous waste facility. No fee.\n\n\n'],
  ['\nHow to recycle\n\nMotor Oil Filters\nIn garbage\nPuncture the oil filter and drain the oil into a container for 24 hours. Seal drained filter in a plastic bag and put in the garbage.\nDrop-off locations\nBring drained or full oil filters to a household hazardous waste facility. No fee.\n\n'],
  ['\nHow to recycle\n\nMugs, Plates or Bowls\nIn garbage\n\nMugs\nPlates\nBowls\n\n\n'],
  ['\nHow to recycle\n\nPaper Napkins\nIn food and yard waste\nPaper napkins and towels that have food or grease on them go in the food and yard waste.\nIn garbage\nPaper napkins and towels used with cleaning products or that have bodily fluids go in the garbage.\n\n'],
  ['\nHow to recycle\n\nSharps \xe2\x80\x93 Needles & Syringes\nHazardous\nThese can\xe2\x80\x99t go in the garbage; they can injure other people.\nTo dispose of syringes, needles, and lancets (also called \xe2\x80\x9csharps\xe2\x80\x9d), you must put them in a rigid and sealable container like a plastic soda bottle. Then bring to a designated disposal location:\n\nIntersection of Airport Way South and South Holgate Street\nIntersection of 27th Avenue South and Cheasty Boulevard South (center median)\nFremont Canal Park (199 North Canal St, Seattle, WA 98103)\nFreeway Park (700 Seneca St)\nMineral Springs Park (1500 North 105th St, Seattle, WA 98133)\nRoxhill Park (2850 SW Roxbury St, Seattle, WA 98126)\nNorth or South transfer stations\n\nIf you find a syringe on public property, report it as illegal dumping.\nIf you are a business and need to dispose of sharps, call the Households Hazards Line at (206) 296-4692.\n\n'],
  ['\nHow to recycle\n\nNewspaper Bags\nIn recycling\nBundle plastic newspaper bags together with other recyclable plastic bags (such as dry cleaner bags or grocery bags). Put bundle into one plastic bag, tie off, and put in the recycling.\nIn garbage\nSingle newspaper bags go in the garbage.\nDid you know?\nSingle plastic bags go in the garbage because they jam the machinery at the recycling facility.\n\n'],
  ['\nHow to recycle\n\nNewspapers\nIn recycling\nNewspaper goes in the recycling.\nIn food and yard waste\nWet or food-soiled newspaper goes in the food and yard waste.\nDid you know?\nClean, recyclable newspaper is not allowed in the garbage.\n\n'],
  ['\nHow to recycle\n\nSpiral Bound Notebooks\nIn recycling\nSpiral bound notebooks go in the recycling. You don\xe2\x80\x99t need to remove the metal or plastic binding.\n\n'],
  ['\nHow to recycle\n\nOffice Furniture & Equipment\nDonate and reuse\nDonate furniture and equipment in good condition to local thrift stores.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item pickup. {{proj[6].rate_text}}\nTransfer station\nBring office furniture and equipment to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nOffice Paper\nIn recycling\nOffice paper and printer paper go in the recycling.\n\n'],
  ['\nHow to recycle\n\nMotor Oil Filters\nIn garbage\nPuncture the oil filter and drain the oil into a container for 24 hours. Seal drained filter in a plastic bag and put in the garbage.\nDrop-off locations\nBring drained or full oil filters to a household hazardous waste facility. No fee.\n\n'],
  ['\nHow to recycle\n\nOil Tanks\nHazardous\nTo learn how to dispose of oil tanks, call our household hazards line at (206) 296-4692. Hours are 9 a.m. \xe2\x80\x93 4:30 p.m., Monday through Friday.\n\n'],
  ['\nHow to recycle\n\nAcetylene Oxygen Tanks\nDrop-off locations\nContact the supplier or manufacturer. In most cases, they will take the tank back at no cost.\nIf the supplier refuses to accept the tank, call (206) 296-4692. You will need to request approval to bring the tank to a household hazardous waste facility.\n\n'],
  ['\nHow to recycle\n\nPacking Peanuts\nIn garbage\nPut packing peanuts in a clear plastic bag and tie closed. Then put in the garbage.\nDrop-off locations\nStyro Recycle in Kent accepts Styrofoam blocks, packing sheets, and packing peanuts for recycling.\n\n'],
  ['\nHow to recycle\n\nStyrofoam Blocks or Packing Sheets\nIn garbage\nStyrofoam blocks and packing sheets go in the garbage.\nDrop-off locations\nStyro Recycle in Kent accepts Styrofoam blocks, packing sheets, and packing peanuts for recycling.\n\n'],
  ['\nHow to recycle\n\nLatex Paint\nIn garbage\n\nDry latex paint by leaving the can open and protected from children and animals.\nSeparate the lid from the dried paint can and put both in your garbage.\n\nTip: You can harden large amounts of latex paint by adding cat litter to the can.\nDrop off locations\nDrop off unused latex paint, in the original container, for a fee at local locations in the Take it Back network\nDid you know?\nThrowing out your dried paint can with the lid removed lets your garbage collector knows the paint is dried.\n\n'],
  ['\nHow to recycle\n\nOil-Based Paint\nHazardous \xe2\x80\x93 no charge\nBring oil-based paint to a household hazardous waste facility. No fee.\nIn garbage\nEmpty oil-based paint cans can go in the garbage:\n\nRemove the lid and let fumes evaporate outside, away from children and animals.\nSeparate the lid from the dried paint can and put both in your garbage.\n\nDid you know?\nThrowing out your dried paint can with the lid removed lets your garbage collector knows the paint is dried.\n\n'],
  ['\nHow to recycle\n\nPaint Cans\nIn garbage\nEmpty latex or oil-based paint cans can go in the garbage:\n\nRemove the lid and let fumes evaporate outside, away from children and animals.\nSeparate the lid from the dried paint can and put both in your garbage.\n\nDid you know?\nThrowing out your dried paint can with the lid removed lets your garbage collector knows the paint is dried.\n\n'],
  ['\nHow to recycle\n\nPainted or Treated Wood\nIn garbage\nPainted or treated wood can go in the garbage:\n\nBreak wood down so it fits in your bin with the lid closed.\nMake sure it doesn\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nTransfer station\nBring lumber and wood boards to city transfer stations. {{proj[1].rate_text}}\n\n'],
  ['\nHow to recycle\n\nPallets\nIn food and yard waste\nBreak pallets made from untreated wood into pieces that are:\n\n4 inches or less in diameter\n4 feet or less in length\nRemove any nails or metallic items.\n\nIn garbage\nPallets made from treated wood can be broken down and put in the garbage:\n\nItems must fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nNext to bin\nItems that do not fit in your bin with the lid closed may be put in a plastic bag and set next to your garbage bin on collection day. {{proj[4].rate_text}}\nTransfer station\nBring pallets to city transfer stations. {{proj[1].rate_text}}\n\n'],
  ['\nHow to recycle\n\nComposite Wood Paneling\nIn garbage\nWood paneling and composite materials can go in the garbage:\n\nBreak paneling down so it fits in your bin with the lid closed.\nMake sure it doesn\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nNext to bin\nPaneling that does not fit in your bin with the lid closed can be put in a plastic bag and set next to your garbage can on collection day. {{proj[4].rate_text}}\nTransfer station\nBring wood paneling and composite materials to city transfer stations. {{proj[1].rate_text}}\n\n'],
  ['\nHow to recycle\n\nPaper Bags\nIn recycling\nClean and dry paper bags go the recycling.\nIn food and yard waste\nFood-soiled bags go in the food and yard waste cart.\n\n'],
  ['\nHow to recycle\n\nPaper Plates or Cups\nIn recycling \xe2\x80\x93 no rinsing needed\n\nPaper cups with a small amount of liquid\nClean paper plates\n\nIn food and yard waste\n\nPaper plates or cups labeled as \xe2\x80\x9cCompostable\xe2\x80\x9d\nUncoated (not shiny) paper plates (such as Chinet brand)\n\nIn garbage\n\nDirty plates and cups with a shiny coating\nStyrofoam plates and cups\n\nDid you know?\nThe shiny coating on paper plates and cups is usually plastic. Scrape the coating with your fingernail or a knife. If wax collects under your fingernail, the coating is wax. Wax-coated cups and plates can go in your food waste bin.\n\n'],
  ['\nHow to recycle\n\nPaper Punch Holes\nIn food and yard waste\nPaper punch holes go in the food and yard waste.\nDid you know?\nPaper punch holes are too small to be recycled at the recycling facility.\n\n'],
  ['\nHow to recycle\n\nPaper Towels\nIn food and yard waste\nPaper towels and napkins that have food or grease on them go in the food and yard waste.\nIn garbage\nPaper towels used with cleaning products or that have bodily fluids on them go in the garbage.\n\n'],
  ['\nHow to recycle\n\nPaper Towel Rolls\nIn recycling\nPaper towel and toilet paper rolls go in the recycling. Glue and small amounts of paper are okay to leave on.\n\n'],
  ['\nHow to recycle\n\nPesticide Containers\nHazardous \xe2\x80\x93 no charge\nBring full or partially-full pesticide containers to your nearest household hazardous waste facility. No fee.\nIn garbage\nEmpty pesticide containers go in the garbage.\nDid you know?\nFind ways to avoid using pesticides from the Garden Hotline.\n\n'],
  ['\nHow to recycle\n\nPesticides\nHazardous \xe2\x80\x93 no charge\nBring pesticides to a household hazardous waste facility. No fee.\nIn garbage\nEmpty pesticide containers go in the garbage.\nDid you know?\nFind ways to avoid using pesticides from the Garden Hotline.\n\n'],
  ['\nHow to recycle\n\nPet Food\nIn food and yard waste\nBoth dry and wet pet food can be turned into valuable compost.\nDid you know?\nWrap wet pet food in newspaper, a paper bag, or a compostable bag to help keep your bin clean.\n\n'],
  ['\nHow to recycle\n\nPet Food Bags\nIn recycling\nPaper pet food bags go in the recycling. Remove any string stitching first.\nIn garbage\nPlastic pet food bags, and bags made of multiple materials, go in the garbage.\n\n'],
  ['\nHow to recycle\n\nPet Waste or Litter\nIn garbage\nBag dog waste, cat waste, and used kitty litter. Tie off the bags and put in the garbage.\nDid you know?\nNever flush kitty litter down the toilet!\nPet waste can\xe2\x80\x99t be composted in the food and yard waste or in backyard composting bins.\n\n'],
  ['\nHow to recycle\n\nPhone Books\nIn recycling\nPhone books go in the recycling.\nDid you know?\nYou can opt out of receiving phone books.\nPhone books aren\xe2\x80\x99t allowed in the garbage.\n\n'],
  ['\nHow to recycle\n\nPhotographs\nIn garbage\nPhotographs go in the garbage.\nDid you know?\nPhotographs aren\xe2\x80\x99t recyclable because of the chemicals used to create them and the short fibers used for their paper.\n\n'],
  ['\nHow to recycle\n\nPizza Boxes\nIn recycling\nPizza boxes that are clean go in the recycling.\nIn food and yard waste\nGreasy or food-soiled pizza boxes go in the food and yard waste.\n\n'],
  ['\nHow to recycle\n\nPlant or Tree Salvage\nIn food and yard waste\nPlants and trees go in the food and yard waste. All pieces must be less than 4-inches in diameter and under 4-feet long.\nDid you know?\nYou can give your plant a new home through your neighborhood Buy Nothing group or PlantAmnesty.\n\n'],
  ['\nHow to recycle\n\nPlant Pots\nIn recycling \xe2\x80\x93 rinse first\nEmpty and rinsed plastic plant pots go in the recycling.\nIn garbage\nDirty or ceramic plant pots go in the garbage.\nDid you know?\nAsk about reuse and recycling options where you buy plant pots. Some garden stores and nurseries will take back plastic pots and reuse them.\n\n'],
  ['\nHow to recycle\n\nPlastic Bottles\nIn recycling \xe2\x80\x93 rinse first\n\nEmpty, clean plastic bottles\nPlastic bottle caps if attached to the empty bottle\n\nIn food and yard waste\n\nBottles labeled \xe2\x80\x9cCompostable\xe2\x80\x9d or \xe2\x80\x9c#7 PLA\xe2\x80\x9d\n\nIn garbage\n\nPesticide bottles\nMotor oil bottles\nOther automotive fluid containers\n\n\n'],
  ['\nHow to recycle\n\nPlastic Cups & Utensils\nIn recycling\n\nEmpty and clean plastic cups\n\nIn garbage\n\nDirty plastic cups\nPlastic utensils\nStyrofoam cups\n\nIn food and yard waste\nPlastic-like containers labeled \xe2\x80\x9cCompostable\xe2\x80\x9d or \xe2\x80\x9c#7 PLA\xe2\x80\x9d go in the food and yard waste.\nLearn more about compostable packaging (pdf).\n\n'],
  ['\nHow to recycle\n\nPeanut Butter or Mayonnaise Jars\nIn recycling\xe2\x80\x94rinse first\nClean jars coated with oily food like peanut butter or mayonnaise with a little bit of water and a brush. Then rinse jar clean.\nIn garbage\nJars coated with oily film that cannot be cleaned off should to go in the garbage.\n\n'],
  ['\nHow to recycle\n\nPlastic Milk or Juice Jugs\nIn recycling \xe2\x80\x93 rinse first\nEmpty milk and juice jugs and bottles go in the recycling.\nPlastic lids and caps can be recycled if attached to the bottle.\n\n'],
  ['\nHow to recycle\n\nPlastic without Recycle Symbol\nIn recycling \xe2\x80\x93 rinse first\n\nYogurt containers\nDeli containers\nBottles and jugs\nMicrowave trays\nPlastic lids 3-inches or larger\nClean and empty plastic grocery bags \xe2\x80\x93 bundle into one bag and tie off\nSmall plastic bottle caps if screwed onto an empty plastic bottle\nClean plastic plant pots\nTupperware\nPill bottles (not prescription vials)\nRigid plastic toys \xe2\x80\x93 3-feet or less on all sides\nRigid plastic sporting equipment \xe2\x80\x93 3-feet or less on all sides\nRigid plastic furniture \xe2\x80\x93 3-feet or less on all sides\nStorage containers\nBuckets with no fabric, foam, or wood attached\n\nIn food and yard waste\nPlastic-like containers labeled \xe2\x80\x9cCompostable\xe2\x80\x9d or \xe2\x80\x9c#7 PLA\xe2\x80\x9d go in the food and yard waste.\nLearn more about compostable packaging (pdf).\nIn garbage\n\nLoose lids less than 3-inches in diameter\nLoose plastic bottle caps\nDirty plastic cups\nPlastic utensils\nBlister packs\nFlexible plastic (such as inflatable pools)\nPlastic molding\nVinyl or plastic blinds\nCD and DVD cases\nPlastic clothes hangers\nPlastic tarps\nZiploc or plastic bread bags\nPlastic liners and trays from food boxes\n\nDid you know?\nSeattle doesn\xe2\x80\x99t recycle by number because it\xe2\x80\x99s not a reliable way to determine the recyclability of an item.\n\n'],
  ['\nHow to recycle\n\nPlastic Outdoor Furniture\nIn recycling\nRigid plastic outdoor furniture can go in the recycling:\n\nShould be 3-feet or less on all sides\nSmall amounts of attached metal (such as hinges) are allowed\nRemove other materials such as fabric, foam, or wood.\n\nNext to bin \xe2\x80\x93 no charge\nLarger rigid plastic outdoor furniture that doesn\xe2\x80\x99t fit in your recycling bin can be set next to the bin on your recycling collection day.\n\n'],
  ['\nHow to recycle\n\nPlastic Food Tubs\nIn recycling\xe2\x80\x94rinse first\n\nPlastic food containers for yogurt, margarine, dips, salsa, etc.\nPlastic lids 3-inches across or larger\n\nIn garbage\n\nContainers with food inside\nLids less than 3-inches across\n\n\n'],
  ['\nHow to recycle\n\nPool or Spa Chemicals\nHazardous \xe2\x80\x93 no charge\nBring pool chemicals to a household hazardous waste facility. No fee.\nPool and spa chemicals aren\xe2\x80\x99t allowed in the garbage.\n\n'],
  ['\nHow to recycle\n\nPorcelain Sinks, Toilets or Tubs\nDonate and reuse\nYou can often donate or resell sinks, toilets, and tubs to building supply stores that specialize in salvage materials.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nIn garbage\nPorcelain sinks and fixtures can go in the garbage if they don\xe2\x80\x99t exceed the weight limits printed on your bin.\nTransfer station\nBring porcelain sinks, toilets, and tubs to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nPots or Pans\nIn recycling\nMetal pots and pans can go in the recycling. They can have small amounts of plastic, wood, or rubber attached.\nIn garbage\nCeramic or glass pots, pans, and lids can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nPrescription Drug Bottles\nIn garbage\nClear plastic prescription medicine vials go the garbage. The plastic is too brittle to recycle.\nIn recycling\nPill bottles, such as aspirin or vitamin bottles, go in the recycling.\nDrop-off locations\nBring medicines to a secure medicine return site.\n\n'],
  ['\nHow to recycle\n\nPrinter Cartridges & Toner\nIn garbage\nPrinter cartridges and toner can go in the garbage.\nDrop-off locations\nSome printer cartridge manufactures and stores that sell printer cartridges will take old cartridges back for recycling.\n\n'],
  ['\nHow to recycle\n\nPrinters & Peripherals\nDrop-off locations\nFind locations to recycle printers and peripherals via the Take It Back Network (fees may apply).\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. Fees apply.\nDid you know?\nPrinters and peripherals can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\nProduce or Bulk Food Bags\nIn garbage\nPlastic bags used for produce and bulk foods go in the garbage.\nDid you know?\nThese bags are not recycled because they often contain food residue or moisture.\n\n'],
  ['\nHow to recycle\n\nPropane Tanks\nHazardous\nLarger, barbeque-sized propane tanks (up to 5-gallons) must go to a household hazardous waste facility. No fee. This includes tanks that are empty or that contain any amount of propane.\nFor tanks larger than 5-gallons, call our household hazards line at (206) 296-4692. Hours are 9 a.m. \xe2\x80\x93 4:30 p.m., Monday through Friday.\nIn garbage\nEmpty propane or gas canisters under 2-pounds can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nRechargeable Appliances\nDonate and reuse\nDonate rechargeable appliances in working condition to local thrift stores or find drop off and mail back recycling options at Call2Recycle outlet.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nHazardous \xe2\x80\x93 no charge\nRemove rechargeable and lithium-ion batteries from appliances and bring the batteries to a household hazardous waste facility. No fee.\nThey can\xe2\x80\x99t go in the garbage.\nIn garbage\nAppliances with the rechargeable batteries removed can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nRechargeable Batteries\nDrop-off locations\nBring rechargeable batteries to city transfer stations. No fee.\nBring rechargeable batteries to a household hazardous waste facility where the materials in the batteries will be reclaimed and recycled. No fee.\nFind drop off and mail back recycling options at Call2Recycle outlet.\nRechargeable batteries can not go in the garbage or recycling cart\n\n'],
  ['\nHow to recycle\n\nRefrigerators or Freezers\nReuse\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nCurb-side pickup\nYou must remove doors and latches from refrigerators and freezers.\n\nCall SPU Customer Service at (206) 684-3000 to request bulky item pickup. {{proj[5].rate_text}}\n\nTransfer station\nBring up to 2 residential refrigerators and freezers per visit to city transfer stations. {{proj[2].rate_text}}\nYou must remove doors and latches from refrigerators and freezers.\n\n'],
  ['\nHow to recycle\n\nReusable Lumber\nIn food and yard waste\nUnpainted and untreated wood can go in the food and yard waste:\n\nPieces should be less than 4-inches in diameter and under 4-feet long to avoid extra fees.\nRemove nails and all other non-wood materials.\nAvoid extra charges \xe2\x80\x93 Break lumber and boards down so they fit in your bin with the lid closed.\n\nIn garbage\nPainted or treated wood can go in the garbage:\n\nAll pieces must be less than 4-inches in diameter and under 4-feet long.\nAvoid extra charges \xe2\x80\x93 Break lumber and boards down so they fit in your bin with the lid closed.\n\nDrop-off locations\nDonate or resell reusable lumber through building supply businesses that specialize in salvage or reusable materials.\n\n'],
  ['\nHow to recycle\n\nRocks or Gravel\nDonate\nGravel in good condition may be accepted by local salvaged building material businesses.\nIn garbage\nRocks and gravel can go in your garbage if they don\xe2\x80\x99t exceed the weight limits printed on your bin, and fit in your bin with the lid completely closed. No individual rock should be larger than 2 feet by 2 feet.\nTransfer station\nBring rocks and gravel to city transfer stations. They are charged as garbage. Charge for garbage is $145 per ton, minimum charge of $30 covers up to 420 lbs.\n\n'],
  ['\nHow to recycle\n\nSalvaged materials\nDonate and reuse\nYou can often donate or resell these items to building supply stores that specialize in salvage materials.\nTransfer station\nBring salvaged building materials to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nScrap Metal\nIn recycling\nMetal parts larger than 3-inches go in the recycling.\n\nRusted metal can be recycled unless the metal is falling apart.\nSmall amounts of plastic, wood, or rubber can be attached.\n\nNext to bin \xe2\x80\x93 no charge\nLarge metal parts can be put at the curb for pickup on your recycling collection day.\n\nThese must be bundled or tied.\nThe maximum size is 2-feet on all sides.\n\nIn garbage\n\nMetal items with large amounts of plastic, wood, or rubber attached\nMetal items that are smaller than 3-inches\n\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item collection. Fees apply.\nDrop-off locations\nAll metal, except car parts, is accepted as recycling at city transfer stations. There is no fee for most metal.\n\nMaximum size is 8-feet long.\nThere is a charge for appliances, limit 2 per load.\n\n\n'],
  ['\nHow to recycle\n\nScrews, Nails, Nuts or Bolts\nIn garbage\nScrews, nails, nuts, bolts, and other metal items smaller than 3-inches go in the garbage.\nDid you know?\nSmall metal items can fall through the sorting machinery at the recycling plant.\n\n'],
  ['\nHow to recycle\n\nShampoo or Lotion Bottles\nIn recycling\nEmpty shampoo and lotion bottles go in the recycling.\nPlastic lids and caps can be recycled if attached to the bottle.\n\n'],
  ['\nHow to recycle\n\nWood Scraps, Shavings, or Sawdust\nIn food and yard waste\nClean, untreated wood shavings, scraps, and sawdust go in the food and yard waste. Put sawdust or shavings in a closed paper bag or box to contain it.\nIn garbage\nPainted or treated wood shavings, scraps, and sawdust go in the garbage. Put sawdust and shavings in a bag and tie off.\n\n'],
  ['\nHow to recycle\n\nSharps \xe2\x80\x93 Needles & Syringes\nHazardous\nThese can\xe2\x80\x99t go in the garbage; they can injure other people.\nTo dispose of syringes, needles, and lancets (also called \xe2\x80\x9csharps\xe2\x80\x9d), you must put them in a rigid and sealable container like a plastic soda bottle. Then bring to a designated disposal location:\n\nIntersection of Airport Way South and South Holgate Street\nIntersection of 27th Avenue South and Cheasty Boulevard South (center median)\nFremont Canal Park (199 North Canal St, Seattle, WA 98103)\nFreeway Park (700 Seneca St)\nMineral Springs Park (1500 North 105th St, Seattle, WA 98133)\nRoxhill Park (2850 SW Roxbury St, Seattle, WA 98126)\nNorth or South transfer stations\n\nIf you find a syringe on public property, report it as illegal dumping.\nIf you are a business and need to dispose of sharps, call the Households Hazards Line at (206) 296-4692.\n\n'],
  ['\nHow to recycle\n\nShredded Paper\nIn recycling\nBag long shredded paper in a clear plastic bag and put in the recycling.\nIn food and yard waste\nSmaller shredded paper like confetti and cross-cut goes in the food and yard waste.\nDid you know?\nShredding paper lowers the quality of the paper fiber for recycling, so it\xe2\x80\x99s best to shred only when necessary.\n\n'],
  ['\nHow to recycle\n\nShrink Wrap\nIn recycling\nClean and dry shrink wrap goes in the recycling:\n\nBundle with bubble wrap or recyclable plastic bags (such as newspaper bags, shopping bags, and dry cleaning bags).\nPut items in a single plastic bag and tie off.\n\nIn garbage\nDirty or un-bagged shrink wrap goes in the garbage.\n\n'],
  ['\nHow to recycle\n\nSilverware\nIn recycling\nSilverware and other metal items 3-inches or larger can go in the recycling. Small amounts of attached rubber, plastic, wood accepted.\nIn garbage\nSilverware and other metal items smaller than 3-inches on all sides can go in the garbage.\n\n'],
  ['\nHow to recycle\n\nMetal Sinks, Tubs or Fixtures\nDonate and reuse\nYou can often donate or resell sinks, tubs, and fixtures to building supply stores that specialize in salvage materials.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nIn recycling\nMetal sinks and fixtures go in the recycling:\n\nThey must be between 3 inches and 2 feet on all sides.\nSmall amounts of plastic, wood, or rubber can be attached.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item pickup. {{proj[6].rate_text}}\nTransfer station\nBring metal sinks, tubs, and fixtures less than 8 feet on all sides to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nToasters\nDonate and reuse\nDonate toasters in good condition to local thrift stores.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nIn garbage\nDamaged toasters, blenders, food processors and mixers can go in the garbage.\nTransfer station\nSome small household appliances can be recycled as scrap metal for free at city transfer stations.\n\n'],
  ['\nHow to recycle\n\nSmoke Detectors\nIn garbage\nSmoke detectors with batteries removed go in the garbage.\nDid you know?\nSome smoke detector manufacturers will take back their old alarms for disposal.\n\n'],
  ['\nHow to recycle\n\nSolvents\nHazardous \xe2\x80\x93 no charge\nBring solvents like paint thinner to a household hazardous waste facility:\n\nPut solvents in a sealed container that is 5-gallons or less.\nLimit 50-gallons per trip.\n\nSolvents aren\xe2\x80\x99t allowed in the garbage.\n\n'],
  ['\nHow to recycle\n\nSoup Boxes\nIn recycling \xe2\x80\x93 rinse first\nPlastic spouts don\xe2\x80\x99t need to be removed to recycle soup boxes. Make sure they are empty and clean.\n\n'],
  ['\nHow to recycle\n\nAerosol Cans\nHazardous \xe2\x80\x93 no charge\nBring cans that contain hazardous materials like paint, solvents, or other flammables to a household hazardous waste facility. No fee.\nIn garbage\n\nEmpty aerosol cans\nPartially full cans with non-hazardous contents\n\n\n'],
  ['\nHow to recycle\n\nStainless Steel\nIn recycling\n\nMetal parts larger than 3-inches go in the recycling.\nSmall amounts of plastic, wood, or rubber can be attached.\n\nNext to bin \xe2\x80\x93 no charge\nLarge metal parts can be put at the curb next to your bin on your recycling collection day.\n\nThese must be bundled or tied.\nThe maximum size is 2-feet on all sides.\n\nIn garbage\n\nMetal items that are smaller than 3-inches.\nMetal items with plastic, wood, or rubber attached.\n\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item collection. Fees apply.\nDrop-off locations\nAll metal, except car parts, is accepted as recycling at city transfer stations. There is no fee for most metal.\n\nMaximum size is 8-feet long.\nThere is a charge for appliances, limit 2 per load.\n\n\n'],
  ['\nHow to recycle\n\nSteel / Tin Cans\nIn recycling \xe2\x80\x93 rinse first\nKeep can lids partially attached or push the lid into the can. You don\xe2\x80\x99t need to remove the can label.\nIn garbage\nLoose can lids (not attached or pushed into the can) go in the garbage.\n\n'],
  ['\nHow to recycle\n\nSteel or Tin Cans & Lids\nIn recycling \xe2\x80\x93 rinse first\nKeep can lids partially attached or push the lid into the can. You don\xe2\x80\x99t need to remove the can label.\nIn garbage\nLoose can lids (not attached or pushed into the can) go in the garbage.\n\n'],
  ['\nHow to recycle\n\nStereo or Audio Equipment\nDonate and reuse\nDonate stereo or audio equipment in good condition to local thrift stores.\nResell or give them away using sites like Craigslist, Freecycle, and Buy Nothing.\nFind locations to recycle studio and audio equipment via the Take It Back Network (fees may apply).\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. {{proj[4].rate_text}}\nDid you know?\nStudio and audio equipment can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\nStoves\nReuse\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request bulky item pickup. {{proj[6].rate_text}}\nTransfer station\nBring up to 2 residential appliances per visit to city transfer stations. {{proj[2].rate_text}}\n\n'],
  ['\nHow to recycle\n\nStyrofoam Blocks\nIn garbage\nStyrofoam blocks and packing sheets go in the garbage.\nDrop-off locations\nStyro Recycle in Kent accepts Styrofoam blocks, packing sheets, and packing peanuts for recycling.\n\n'],
  ['\nHow to recycle\n\nTake-Out Containers\nIn recycling \xe2\x80\x93 rinse first\n\nEmpty and rinsed plastic clamshell containers\nEmpty and rinsed plastic-coated (shiny) paper containers\n\nIn food and yard waste\n\nDirty or clean uncoated (not shiny) paper take-out containers\nDirty or clean take-out containers labeled \xe2\x80\x9cCompostable\xe2\x80\x9d or \xe2\x80\x9c#7 PLA\xe2\x80\x9d\nGreasy pizza boxes\n\nLearn more about compostable packaging (pdf).\nIn garbage\n\nStyrofoam containers\nDirty plastic-coated (shiny) paper containers\nDirty plastic containers that aren\xe2\x80\x99t marked \xe2\x80\x9cCompostable\xe2\x80\x9d or \xe2\x80\x9c#7 PLA\xe2\x80\x9d\n\n\n'],
  ['\nHow to recycle\n\nTelevisions\nDrop-off locations\nFind locations to recycle TVs via the Take It Back Network.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. Fees apply.\nDid you know?\nTelevisions and other electronics can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\nAseptic or Tetra Pak\nIn recycling \xe2\x80\x93 rinse first\n\nEmpty milk, juice, and soup cartons\nCartons labeled Tetra Pak\nOther aseptic cartons\n\nPlastic spouts don\xc3\xa2\xc2\x80\xc2\x99t need to be removed to recycle Tetra Pak cartons. Caps should be removed and placed in the garbage.\n\n'],
  ['\nHow to recycle\n\nReceipts\nIn recycling\nPaper and thermal paper receipts go in the recycling.\n\n'],
  ['\nHow to recycle\n\nTires\nDrop-off locations\nBring up to 4 tires per visit to city transfer stations. Fees apply.\n\n'],
  ['\nHow to recycle\n\nToys or Sporting Goods\nDonate and reuse\nDonate toys or sporting goods in good condition to local thrift stores.\nResell or give it away using sites like Craigslist, Freecycle, and Buy Nothing.\nIn recycling\n\nClean metal toys and sporting equipment 2 feet or less on all sides. Can include small amounts of attached plastic, rubber, or wood.\nClean rigid plastic toys and sporting equipment 3 feet or less on all sides.\n\nIn garbage\nSports equipment and toys not made of metal or rigid plastic.\nTransfer station\nToys and sporting equipment greater than the above size limits can be taken to city transfer stations. Charge is $30 per trip or $145 per ton if part of a larger load ($30 minimum charge covers up to 420lbs).\n\n'],
  ['\nHow to recycle\n\nTrees or Brush\nIn food and yard waste\nTrees, brush, and branches go in the food and yard waste:\n\nCut down to 4 inches or less in diameter and 4 feet or less in length.\nAvoid extra charges \xe2\x80\x93 Items should fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nNext to bin\nBundle trees and brush and set next to the bin. {{proj[7].rate_text}}\n\nTie bundles with natural twine. No plastic allowed.\nBundles must be 2 feet or less in diameter.\n\nTransfer station\nBring trees and brush to city transfer stations. {{proj[1].rate_text}}\n\nAll trees, brush, or branches must be 8 feet or less in length.\nAll pieces must be 8 inches or less in diameter.\n\n\n'],
  ['\nHow to recycle\n\nPlastic Food Tubs\nIn recycling\xe2\x80\x94rinse first\n\nPlastic food containers for yogurt, margarine, dips, salsa, etc.\nPlastic lids 3-inches across or larger\n\nIn garbage\n\nContainers with food inside\nLids less than 3-inches across\n\n\n'],
  ['\nHow to recycle\n\nStyrofoam Cups\nIn garbage\nStyrofoam cups go in the garbage.\n\n'],
  ['\nHow to recycle\n\nVCRs\nDrop-off locations\nFind locations to recycle VCRs via the Take It Back Network.\nCurb-side pickup\nCall SPU Customer Service at (206) 684-3000 to request curbside electronics pickup. Fees apply.\nDid you know?\nVCRs can\xe2\x80\x99t go in the garbage because they contain materials harmful to people, animals, and the environment.\n\n'],
  ['\nHow to recycle\n\nVitamins\nIn garbage\nPut vitamins in a closed bottle or bag and put in the garbage.\n\n'],
  ['\nHow to recycle\n\nOther Vehicle Fluids\nCaution: Don\xe2\x80\x99t mix fluids with used motor oil!\nHazardous \xe2\x80\x93 no charge\nBring automotive fluids (such as brake, transmission, hydraulic, or power steering fluids) to a household hazardous waste facility:\n\nPut fluids in a sealed container that is 5-gallons or less.\nLimit 50-gallons per trip.\n\n\n'],
  ['\nHow to recycle\n\nWindows or Picture Glass\nDonate\nSome building supply or second use stores accept unbroken windows or other glass in good condition.\nIn garbage\nUnbroken windows and window glass can go in the garbage:\n\nItems must fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nTransfer station\nBring windows and glass to city transfer stations. {{proj[0].rate_text}}\n\n'],
  ['\nHow to recycle\n\nFlushable Wipes\nIn garbage\nBaby wipes, wet wipes, cleaning wipes, and any wipes labeled \xe2\x80\x9cflushable\xe2\x80\x9d go in your garbage.\nIf flushed down your toilet, they can clog your sewer pipes.\n\n'],
  ['\nHow to recycle\n\nWire Clothes Hangers\nDonate and reuse\nDonate wire clothes hangers in good condition to local thrift stores.\nCheck with local dry cleaners. They may accept wire hangers.\nIn garbage\nWire clothes hangers can go in the garbage.\nDid you know?\nWire hangers get tangled in the machinery at the recycling processing facility, which is why they can\xe2\x80\x99t be recycled.\n\n'],
  ['\nHow to recycle\n\nClean Wood Waste\nIn food and yard waste\nClean, untreated and unpainted wood goes in the food and yard waste.\n\nAll pieces must be 4 inches or less in diameter and 4 feet or less in length.\nPut sawdust or shavings in paper bags or boxes to keep from scattering.\nAvoid extra charges \xe2\x80\x93 Items should fit in your bin with the lid closed.\nDon\xe2\x80\x99t exceed the weight limits printed on your bin.\n\nNext to bin\nBundles can be set next to the bin. {{proj[7].rate_text}}\n\nTie bundles with natural twine. No plastic allowed.\nBundles must be 2 feet or less in diameter.\n\nTransfer station\nBring untreated wood waste to city transfer stations. {{proj[1].rate_text}}\n\nAll pieces must be 4 feet or less in length and 4 inches or less in diameter.\nNails and staples are okay.\n\nDid you know?\nCompost processing equipment removes metal staples and nails. However, the equipment can\xe2\x80\x99t remove plastic.\n\n'],
  ['\nHow to recycle\n\nZiploc Bags\nIn garbage\nZiploc or other plastic food bags go in the garbage.\nDid you know?\nZiploc and plastic food bags contain more than one type of plastic that can\xe2\x80\x99t be recycled together. They also often contain food residue and moisture that contaminate recycling.\n\n']]




function parseStr (arr){
  let allItemArray = [];
  let allItemObjects = [];

  let destination = ['GARBAGE', 'RECYCLING', 'YARD', 'REUSE', 'HAZARD', 'TRANSFER', 'BINSIDE', ];

  let material = ['PLASTIC', 'PAPER', 'ALUMINUM', 'GLASS', 'FOOD', 'APPLIANCE', 'ELECTRONIC'];

  let inGarbage = ['DIRTY', 'FOOD-COVERED']


  arr.forEach((html, idx)=>{
    //console.log('where it is breaking: ', html, idx);

    //console.log('type: ', typeof(html[0]));

    var itemPageResults = html[0].split('\n');
    // console.log(itemPageResults);

    var newItemArray = [];

    for (let i = 0; i<itemPageResults.length; i++){
      if(itemPageResults[i]){
        newItemArray.push(itemPageResults[i]);
      }
    }

    //console.log(newItemArray);

    let garbageWords = '';
    newItemArray.forEach((line, idx) =>{

      if(line.includes('In garbage')){
        //console.log('includes in garbage');
        for(let i = 0; i<inGarbage.length; i++){
          if(newItemArray[idx+1].toUpperCase().includes(inGarbage[i])){
            //console.log('word ' + inGarbage[i]);
            garbageWords='dirty';
          }
        }
      }
    })

    let strArray = newItemArray.join().toUpperCase();
    let newItemMaterials = [];
    newItemArray.push(newItemMaterials);

    material.forEach(mat => {
      let itemMaterial = null;
      if(strArray.includes(mat)){
        itemMaterial = mat;
        newItemArray[newItemArray.length-1].push(itemMaterial);
      }
      else{
        newItemArray[newItemArray.length-1].push('OTHER');
      }
    })

    destination.forEach((des, idx)=>{

      if(strArray.includes(des)){
        if(des==='GARBAGE' && garbageWords){
          newItemArray.push([des, 'dirty']);
        }
        else{
          newItemArray.push([des, true]);
        }
      }
      else{
        newItemArray.push([des, null]);
      }
    })

    allItemArray.push(newItemArray);

    //if a category matches, create a new object for the item
    if(newItemArray[newItemArray.length-8][0]){
      allItemObjects.push(new ItemObject(newItemArray));
    }

    allItemObjects = allItemObjects.sort((a, b)=>{
      //console.log('cat: ', a.category, b.category);
      if(a.category < b.category){
        return -1;
      }
      if(a.category > b.category){
        return 1;
      }
     return 0;
    })
  })
  console.log(JSON.stringify({allItemObjects}));
  //console.log(JSON.stringify({allItems: allItemObjects}));
  //return JSON.stringify(allItemObjects);
}

parseStr(itemStr);


function ItemObject (array){
  this.itemName = array[1];
  this.category = array[array.length-8][0],
  this.subcategory = 's',
  this.destination = {
    garbage: array[array.length-7][1],
    recycling: array[array.length-6][1],
    yard: array[array.length-5][1],
    reuse: array[array.length-4][1],
    hazard: array[array.length-3][1],
    transfer: array[array.length-2][1],
    binside: array[array.length-1][1],
  }

}
